version: '3.8'

services:
  mysql:
    container_name: premierleaguedb
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: premierleague
      MYSQL_ROOT_PASSWORD: 1234

    ports:
      - "3307:3306"
    hostname: VIP

    volumes:
      - ./data:/var/lib/mysql
